### ISSUE TITLE
Textured rotated cube example?

### ISSUE THREAD

**Issue by shazz** [almarklein/wgpu-py#103]
Hi,

I'm discovering wgpu and it looks very nice but I'm far from my level of comfort (openGL)... Could you add a little example to display a textured rotated cube ?

I succesfully integrated wgpu and headless pygame (for other stuff: sound effect, keyboard/joystick events, 2D surface manipulation) but now I'd like to replace my openGL code to map a surface on a quad with wgpu.

I found some javascript examples but not (yet) straight forward to port.

Thanks !

**Comment by Korijn** [comment]
https://github.com/almarklein/wgpu-py/blob/master/examples/cube_glfw.py

:) thanks for using the library!

**Comment by shazz** [comment]
Thanks!
Uh, I did not see this example before, only the triangle... I should be blind!

Yeah, when you 're used to Python and do a lot in a few lines... that looks pretty "complicated" for a simple example (Not really complicated but a lot of code to do few).
So I guess some helper classes on top of it won't be totally useless (at least I will write some)

Concerning pygame, let me finish the wgpu+glfw+pygame integration and I'll share it for sure!

**Comment by almarklein** [comment]
> I did not see this example before, only the triangle

It was added recently :)

> So I guess some helper classes on top of it won't be totally useless

Absolutely! WGPU is still a bit more verbose than OpenGL. That said, the focus of `wgpu-py` is to provide exactly this API. Any higher level abstractions should be implemented in other libraries. E.g. we're working on a ThreeJS-like render engine in [visvis2](https://github.com/almarklein/visvis2) (beware, this project will be renamed soonish).

There is currently one exception where we do provide an abstraction: `wgpu.utils.compute_with_buffers()`
