### ISSUE TITLE
Ship with binary libs in our wheels

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#11]

**Comment by Korijn** [comment]
FYI `setup.py` has already been configured to include any binaries in the `wgpu.resources` folder, we just don't include them yet.

The idea is to have our friends build wgpu-native binaries upstream (see https://github.com/gfx-rs/wgpu/issues/414) and to provide a simple download script in this repo that can be used in development and on CI to acquire the binaries.

**Comment by Korijn** [comment]
https://github.com/gfx-rs/wgpu/pull/416 was merged. Until they perform a release, we can use a snapshot build I released on my fork: https://github.com/Korijn/wgpu/releases/tag/v0.5dev
