### ISSUE TITLE
Tests ... we need tests

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#12]
Let's start with flake checks, btw.

**Comment by Korijn** [comment]
FYI latest flake8 gives 568 warnings, after setting max_line_length to 120 it's 227

**Comment by almarklein** [comment]
Some of these types are actually flags or enums. The codegen simply does not resolve them further yet. Others are "descriptors" which we simply have to explain in the docs.

**Comment by almarklein** [comment]
`max_line_length` can be 88, btw, because we use black

**Comment by Korijn** [comment]
I propose ignoring the flake8 max line length warning and also providing type definitions so the type hints can be properly resolved. It's very hard to combine black and flake8 compliance with the codegen-script...
