### ISSUE TITLE
Generate (API) docs

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#13]
Sphinx autodoc etc. upload to rtd. Should not be too hard. Mostly for reference docs for now.

**Comment by Korijn** [comment]
Might want to reference this website as well; https://sotrh.github.io/learn-wgpu/

**Comment by almarklein** [comment]
Done :)

**Comment by almarklein** [comment]
No wait, I had a link to https://rust-tutorials.github.io/learn-wgpu/buffer-creation.html

**Comment by almarklein** [comment]
Closed by #79
