### ISSUE TITLE
BaseCanvas._draw_frame_and_present swallowing errors

### ISSUE THREAD

**Issue by Korijn** [almarklein/wgpu-py#16]
Currently the `except` in `BaseCanvas._drawFrameAndPresent` swallows errors and writes to stderr.

I think users will want to bring their own implementation for logging, and I also think some users will prefer to see errors bubble up to the top of the stack (where they may be logged or handled centrally for example) rather than be silently swallowed.

In short, the post-mortem debugging implementation probably has its use in development, but maybe it should be behind a flag?

**Comment by almarklein** [comment]
The motivation is that the this function not called by the user, but the GUI toolkit would call it when an update is needed. Either the gui/eventloop will print and swallow the error, or it will crash the whole program.

**Comment by Korijn** [comment]
I can see that, but I don't think that addresses the concern here?
