### ISSUE TITLE
Fix triple quote issue on azure pipelines

### ISSUE THREAD

**Issue by Korijn** [almarklein/wgpu-py#42]
It's unclear why but there are additional quotes at the end of the TAG variable... sometimes? It's causing the condition to fail even when it should succeed. :/

```
Evaluating: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['TAG']))
Expanded: and(True, eq('merge', 'v0.1.2-2-g166d188'''))
                                                  ^^
```

**Comment by Korijn** [comment]
There _are_ builds where the issue doesn't happen... mysterious...

```
Expanded: and(True, eq('merge', 'v0.1.2-12-g3c8bc5a'))
```

https://dev.azure.com/almarklein/wgpu-py/_build/results?buildId=187&view=logs&jobId=8d802004-fbbb-5f17-b73e-f23de0c1dec8&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=34a2a427-865b-5611-5635-0b157c070b5a

**Comment by almarklein** [comment]
That's even worse than if it would fail consistently :(

**Comment by Korijn** [comment]
Well, I think we can work around this by evaluating the expression in bash instead, and setting the result as a variable to use for the step conditions

**Comment by Korijn** [comment]
I got this [to work for wgpu-bin](https://github.com/Korijn/wgpu-bin/pull/4/files#diff-fec826feae04e51c0d94076385408bdcR135-R145), will port the changes to this project.
