### ISSUE TITLE
Triangle example: white window that closes after 1 second (Windows 10)

### ISSUE THREAD

**Issue by niklaskorz** [almarklein/wgpu-py#52]
Running the triangle example with GLFW on Windows 10 (up to date, i.e. running the last Fall update) gives me a white window that exits shortly afterwards.
Using the tkinter canvas exits immediately without even showing a window.
I'm running a Surface Book 2 which has an integrated Intel GPU as well as a dedicated Nvidia GeForce 1050. My graphics drivers are up to date, both Intel and Nvidia. I can compile and run OpenGL and Vulkan applications just fine, so hardware support should not be the issue. A rough guess would be that wgpu-py fails to select the adapter because two are available, but I can't say for sure as I don't know the internals of wgpu.

**Comment by niklaskorz** [comment]
As a side note, I *love* the idea of writing shaders directly in Python and compiling them to SPIR-V. Ingenious move!

**Comment by almarklein** [comment]
Are there any errors printed?

**Comment by niklaskorz** [comment]
Ok, this is quite interesting: I have re-run the command a few times. Most of the time, it just show the white window and then quits, without any error messages.

A few times, it actually displays an error:
```
PS examples (tags/v0.1.3) python3 triangle_glfw.py
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', src\libcore\result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

And once, it started without errors and displayed the triangle:
![image](https://user-images.githubusercontent.com/590517/73926434-eb387f80-48cf-11ea-896d-0ce28faa8f6a.png)

Directly afterwards (i.e., after starting the program again), it resumed to showing a white window and quitting without any errors.

**Comment by niklaskorz** [comment]
To give an idea of how chaotic it actually looks, here is another successful run in 15 tries:

![image](https://user-images.githubusercontent.com/590517/73926748-6bf77b80-48d0-11ea-93bb-ff5784fc2bb1.png)

**Comment by almarklein** [comment]
Welcome to the bleeding edge ;)

I think I've seen that error too, but only occasionally, and usually all subsequent tries run fine. Interesting, an UTF-8 error. There's only 1 or 2 places where we feed a string to wgpu. I'll have a look if something odd is going on there ...

**Comment by Korijn** [comment]
FYI: this is all early days and we are using master branch builds from the upstream wgpu rust project. It might just be a bug there.

**Comment by niklaskorz** [comment]
Thanks for the fast response! I'm very excited about the future of WebGPU, both for use cases on the web as well as outside, so I'm trying to dig a bit deeper into the topic. 😄 

Just to make sure, I have run the cube example of [wgpu-rs](https://github.com/gfx-rs/wgpu-rs), which is using commit [009bde0](https://github.com/gfx-rs/wgpu/tree/009bde0f90d581ef4112978c1d1f3edc14f38e1e) of wgpu. It executes fine on each try:

![image](https://user-images.githubusercontent.com/590517/73928337-343e0300-48d3-11ea-886d-38022feb8464.png)

There have only been [six commits](https://github.com/gfx-rs/wgpu/commits/master) since then, but I don't know if any of those could be the issue.

**Comment by niklaskorz** [comment]
Actually, wgpu-py downloads the last release of wgpu, not the last commit? In that case, both wgpu-rs and wgpu-py use the same version of wgpu.

**Comment by niklaskorz** [comment]
I have been using Python 3.7 provided by Microsoft through the Windows Store. I uninstalled the Windows Store version and installed Python 3.8.1 using the official installer. It all works now, so either something weird is going on in Python 3.7 or in Microsoft's distribution of it.
Either way, everything works as expected now.

**Comment by Korijn** [comment]
> Actually, wgpu-py downloads the last release of wgpu, not the last commit? In that case, both wgpu-rs and wgpu-py use the same version of wgpu.

We build our own binaries over at https://github.com/Korijn/wgpu-bin/ since we need a couple more flavours than the upstream project provides us with (32 bit builds and manylinux1 compatible binaries). That repo contains just a CI script to do the work for us.

As you can see in the [commit-sha](https://github.com/Korijn/wgpu-bin/releases/download/v0.5dev5/commit-sha) of the last build we published, we are running commit https://github.com/gfx-rs/wgpu/tree/gc59e35e

**Comment by niklaskorz** [comment]
@Korijn the commit exists, it is https://github.com/gfx-rs/wgpu/tree/mozilla-646613d3969290c44c08b7a43ee00a6dc5cff4ff (from your linked commit-sha). I don't know what the suffix `-89-gc59e35e` is referring to, but it looks like that's something else, not the commit.

**Comment by Korijn** [comment]
Here's how to read the output of `git describe`: https://git-scm.com/docs/git-describe#_examples

In this case it means `mozilla-646613d3969290c44c08b7a43ee00a6dc5cff4ff` is the most recent tag, it's been `89` commits since then, and the commit itself is `gc59e35e`.

**Comment by almarklein** [comment]
I think I am onto the course of the error. I found that the error occurs more often when drawing multiple pipelines, so I now have a way to trigger this in a pretty reproducible way.

It looks like the cause is ffi objects being cleaned up by the garbage collector (and the memory re-used for something else). The thing is that some structs have fields that are *pointers* to other structs (as opposed to sub-structs). We need to keep these alive.

Now to find a good way to solve this. I hope we can automate this ... to keep the code clean and avoid missing a case.

**Comment by Korijn** [comment]
Do you know specifically which pointer might be the culprit?

**Comment by almarklein** [comment]
The `createRenderPipeline` method has quite a few cases, and the entry point strings (*cough* pointers to char arrays) are at least a trigger (thus the utf-8 error). Also `createComputePipeline` has no such cases, which is why we've never run into this with our tests :)

**Comment by almarklein** [comment]
So now I'm scared we fix it but then miss one case and it will haunt us with Heisenberg bugs later, when we've forgotten about this issue. So I hope we can fix it in a "scalable" way.

**Comment by Korijn** [comment]
I guess we need to start by determining the lifetime of these objects then? So we can tie them to an appropriate scope that will keep them alive as appropriate.

**Comment by almarklein** [comment]
mmm, some more testing suggests that they only need to survive until the actual wgpu api call.

**Comment by Korijn** [comment]
you might be able to forcibly reproduce by calling `gc.collect` https://docs.python.org/3.5/library/gc.html#gc.collect

**Comment by shazz** [comment]
Hi,
I usually code on my linux laptop and it works fine but today I tried my code on my win10 laptop and it seems I have the same problem.

I ran the triangle_glfw.py example and as described a window with a white background opens then closes after 1s and absolutely nothing printed in the console.

I'm suing:
````
glfw==1.11.0
python-shader==0.4.2
wgpu==0.2.0
````

Something I can try?

**Comment by almarklein** [comment]
We should update to the latest wgpu-native and do a new release. Things are moving fast, so this might well fix it.

**Comment by shazz** [comment]
Ok! Please tell when it is ready and I will try. Thanks!
