### ISSUE TITLE
Adopt snake_case instead of camelCase

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#57]
This is a Python lib.

**Comment by almarklein** [comment]
@Korijn I think enums and flags can be kept as they are, what do you think?
```py
# e.g. enums
wgpu.TextureFormat.rgba32float
wgpu.PrimitiveTopology.triangle_strip
# e.g. flags
wgpu.BufferUsage.STORAGE | wgpu.BufferUsage.MAP_READ 
```

**Comment by Korijn** [comment]
https://pep8.org/#prescriptive-naming-conventions

You can try running https://pypi.org/project/pep8-naming/ to see if it flags anything.

**Comment by almarklein** [comment]
Running `flake8` with `pep8-naming` installed gives: ` N816 variable 'bufferUsage' in global scope should not be mixedCase`. 

The flake8 docs don't seem to mention enums or flags, but the [docs on enums](https://docs.python.org/3/library/enum.html) seem pretty clearly advocating the use of CamelCase. We currently do not define enums/flags using classes, but they still represent the same thing. So I'm leaning to keeping them CamelCase.

**Comment by Korijn** [comment]
> Running `flake8` with `pep8-naming` installed gives: ` N816 variable 'bufferUsage' in global scope should not be mixedCase`.

I don't see any usage of `bufferUsage`, only `BufferUsage`, in the code. That's odd.

> The flake8 docs don't seem to mention enums or flags, but the [docs on enums](https://docs.python.org/3/library/enum.html) seem pretty clearly advocating the use of CamelCase. We currently do not define enums/flags using classes, but they still represent the same thing. So I'm leaning to keeping them CamelCase.

Agree

**Comment by almarklein** [comment]
>  don't see any usage of bufferUsage, only BufferUsage, in the code. That's odd.

It's in `flags.py`, but anyway, it mostly served as an example.
