### ISSUE TITLE
Drop Tk support?

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#69]
* On Linux: seems impossible to make it work.
* On macOS: Dito. 
* On Windows: works, but painting occurs *after* the actual paint event, so there is flicker.
* No high-res support.

The only advantage is that Tk is always there (unless you have a mac). But `glfw` does a great job at providing a lean GUI that is very easy to install (binaries also ship on Linux since a few weeks).

Is it worth keeping the backend around only for a shitty solution on Windows?

**Comment by Korijn** [comment]
Nahh, not worth it :)
