### ISSUE TITLE
Support for grayscale textures

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#73]
Currently, textures of format `r8unorm` and `r8uint` work, but `r16sint`, `r32sint` and `r32float` fail. I've not yet been able to find out why.

**Comment by Korijn** [comment]
Are these formats known to work in wgpu-native upstream?

**Comment by almarklein** [comment]
When I asked last week or so, they responded to not have trouble with them earlier. But then again, it does work with uint8 textures. At the time I did not have the tests to say what exactly worked and what not. Let's wait for their next release and if it then still fails I'll ask for help.

**Comment by almarklein** [comment]
https://github.com/gfx-rs/wgpu/issues/575

**Comment by almarklein** [comment]
I tweaked a Rust example to use R16Sint and R32Sint textures and that seemed to work. Should compare that example's wgpu calls, and compare the SpirV that comes off that fragment shader with our SpirV ...
