### ISSUE TITLE
Make things work on Linux and OS X

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#8]
There's a few places where we need to triage over the platform. Only Windows has been implemented so far.

**Comment by Korijn** [comment]
Since we already have crossplatform CI, it should be easy to achieve this with some decent tests.

We can enable screen sessions / configure screen resolution on CI if needed too.

**Comment by almarklein** [comment]
Spinning up an Ubuntu VM and my old macbook should do the trick at first. But yeah, we need more tests too :)

**Comment by Korijn** [comment]
I'm working on Ubuntu at the office and Windows at home, so I should be able to pitch in some Ubuntu support as well.

**Comment by almarklein** [comment]
We need the binaries (e.g. from https://github.com/gfx-rs/wgpu/pull/416) anyway :)  (or setup a rust build environment).

**Comment by Korijn** [comment]
Did a little bit of the work for this in #24 ; we can start testing on all platforms now

**Comment by almarklein** [comment]
Most of the implementation is done in #27, tracking further in #28 and #29
