### ISSUE TITLE
Prevent passing invalid keys in dict arguments

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#95]
Some functions have arguments that are dicts (and some even contain sub-dicts). At the moment, we just take values from the dict, but we do not check whether the dict contains invalid values. This means that typos can cause the wrapper to use the value of the intended key instead, and thus lead to odd behavior.

**Comment by Korijn** [comment]
I'm a little worried that this might lead to the implementation of argument validation which can have significant overhead since it would be implemented at such a low level...

**Comment by almarklein** [comment]
I don't want to go there, because we should rely on wgpu-natvie for argument validation. Yeah performance is important here.
